### PR TITLE
Rework `Scaffold` to avoid Subcompose & fix insets consumption

### LINKED ISSUE #376: Properly support nested Scaffolds/insets
Implement insets consumption, yet this is blocked by https://issuetracker.google.com/issues/273885002

### LINKED ISSUE #500: Consider moving Scaffold from using subcompose layout
Inspiration in https://android-review.googlesource.com/c/platform/frameworks/support/+/2690433

### PR DESCRIPTION
**Pull request by hrach**
closes #500
closes #376

### CODE REVIEW

File: ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Scaffold.kt [hunk 1]
```diff
@@ -86,62 +92,88 @@ private fun ScaffoldLayout(
...
-                    contentInsets.calculateBottomPadding()
-                }
-            },
-            start = contentInsets.calculateStartPadding(layoutDirection),
-            end = contentInsets.calculateEndPadding(layoutDirection),
-        )
-        val contentPlaceables = subcompose(SlotContent) {
-            content(innerPadding)
-        }.map { it.measure(contentConstraints) }
+        // If there is fade, let's do not subtract it, we want content to be shown bellow it.
```
Comment (Drekorian) [inline ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Scaffold.kt:158]:
```suggestion
        // If there is fade, let's do not subtract it, we want the content to be shown below it.
```

**Review by Drekorian — APPROVED** [review]
